site_name: CSDN
site_description: an example blog set up following the tutorial
site_url: https://bikesea.github.io/CSDN

theme:
  name: material
  language: zh
  palette:
  
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - blog

